const int BITS_NORMAL = 1;
const int BITS_CAPTURE = 2;
const int BITS_BIG_PAWN = 4;
const int BITS_EP_CAPTURE = 8;
const int BITS_PROMOTION = 16;
const int BITS_KSIDE_CASTLE = 32;
const int BITS_QSIDE_CASTLE = 64;

const Map<String, int> BITS = {
  'NORMAL': BITS_NORMAL,
  'CAPTURE': BITS_CAPTURE,
  'BIG_PAWN': BITS_BIG_PAWN,
  'EP_CAPTURE': BITS_EP_CAPTURE,
  'PROMOTION': BITS_PROMOTION,
  'KSIDE_CASTLE': BITS_KSIDE_CASTLE,
  'QSIDE_CASTLE': BITS_QSIDE_CASTLE
};
